<?php

declare(strict_types=1);

namespace BizHub\Bookkeeping\Entities;

use BizHub\Bookkeeping\Enums\RecurringOccurrenceStatus;
use DateTimeImmutable;
use InvalidArgumentException;

/**
 * One due date generated by cron from a RecurringTemplate, awaiting the
 * client's decision - confirm (optionally editing amount/date) posts a
 * real journal entry via TransactionCaptureService; skip never posts.
 *
 * @package BizHub\Bookkeeping\Entities
 */
final readonly class RecurringOccurrence
{
    public function __construct(
        public string $uuid,
        public string $templateUuid,
        public string $companyUuid,
        public DateTimeImmutable $dueDate,
        public RecurringOccurrenceStatus $status,
        public ?string $journalEntryUuid,
        public DateTimeImmutable $generatedAt,
        public ?DateTimeImmutable $resolvedAt = null
    ) {
        if ($this->uuid === '') {
            throw new InvalidArgumentException('RecurringOccurrence uuid cannot be empty.');
        }

        if ($this->templateUuid === '') {
            throw new InvalidArgumentException('RecurringOccurrence templateUuid cannot be empty.');
        }

        if ($this->companyUuid === '') {
            throw new InvalidArgumentException('RecurringOccurrence companyUuid cannot be empty.');
        }
    }

    public function withPosted(string $journalEntryUuid, DateTimeImmutable $resolvedAt): self
    {
        return new self(
            $this->uuid,
            $this->templateUuid,
            $this->companyUuid,
            $this->dueDate,
            RecurringOccurrenceStatus::Posted,
            $journalEntryUuid,
            $this->generatedAt,
            $resolvedAt
        );
    }

    public function withSkipped(DateTimeImmutable $resolvedAt): self
    {
        return new self(
            $this->uuid,
            $this->templateUuid,
            $this->companyUuid,
            $this->dueDate,
            RecurringOccurrenceStatus::Skipped,
            $this->journalEntryUuid,
            $this->generatedAt,
            $resolvedAt
        );
    }
}
